/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package session_manage;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import javax.swing.JPanel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

import itpm.Main;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.ImageIcon;

/**
 *
 * 
 */
public class session_main extends javax.swing.JFrame {

    normal_session normalsession;

    public session_main() {
    	getContentPane().setBackground(new Color(102, 153, 204));
        initComponents();
        initComponents();
        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(new Dimension(1920, 1080));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 526, Short.MAX_VALUE)
        );
        jPanel2 = new javax.swing.JPanel();
        
                jPanel2.setBackground(new java.awt.Color(102, 153, 204));
                jButton4 = new javax.swing.JButton();
                jButton4.setFont(new Font("Tahoma", Font.BOLD, 15));
                
                        jButton4.setText("Non Overlapping");
                        jButton4.addActionListener(new java.awt.event.ActionListener() {
                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                jButton4ActionPerformed(evt);
                            }
                        });
                        jButton2 = new javax.swing.JButton();
                        jButton2.setFont(new Font("Tahoma", Font.BOLD, 15));
                        
                                jButton2.setText("Normal Session");
                                jButton2.addActionListener(new java.awt.event.ActionListener() {
                                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                                        jButton2ActionPerformed(evt);
                                    }
                                });
                                jButton1 = new javax.swing.JButton();
                                jButton1.setFont(new Font("Tahoma", Font.BOLD, 15));
                                
                                        jButton1.setText("Consecetive Session");
                                        jButton1.addActionListener(new java.awt.event.ActionListener() {
                                            public void actionPerformed(java.awt.event.ActionEvent evt) {
                                                jButton1ActionPerformed(evt);
                                            }
                                        });
                                        jButton3 = new javax.swing.JButton();
                                        jButton3.setFont(new Font("Tahoma", Font.BOLD, 15));
                                        
                                                jButton3.setText("Session Parelel");
                                                jButton3.addActionListener(new java.awt.event.ActionListener() {
                                                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                                                        jButton3ActionPerformed(evt);
                                                    }
                                                });
                                                
                                                        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                                                        jPanel2Layout.setHorizontalGroup(
                                                        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
                                                        		.addGroup(jPanel2Layout.createSequentialGroup()
                                                        			.addGap(59)
                                                        			.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 209, GroupLayout.PREFERRED_SIZE)
                                                        			.addGap(55)
                                                        			.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 241, GroupLayout.PREFERRED_SIZE)
                                                        			.addGap(39)
                                                        			.addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 234, GroupLayout.PREFERRED_SIZE)
                                                        			.addGap(43)
                                                        			.addComponent(jButton4, GroupLayout.PREFERRED_SIZE, 249, GroupLayout.PREFERRED_SIZE)
                                                        			.addContainerGap(109, Short.MAX_VALUE))
                                                        );
                                                        jPanel2Layout.setVerticalGroup(
                                                        	jPanel2Layout.createParallelGroup(Alignment.TRAILING)
                                                        		.addGroup(jPanel2Layout.createSequentialGroup()
                                                        			.addContainerGap(23, Short.MAX_VALUE)
                                                        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
                                                        				.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 61, GroupLayout.PREFERRED_SIZE)
                                                        				.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 61, GroupLayout.PREFERRED_SIZE)
                                                        				.addComponent(jButton3, GroupLayout.PREFERRED_SIZE, 61, GroupLayout.PREFERRED_SIZE)
                                                        				.addComponent(jButton4, GroupLayout.PREFERRED_SIZE, 61, GroupLayout.PREFERRED_SIZE))
                                                        			.addGap(19))
                                                        );
                                                        jPanel2.setLayout(jPanel2Layout);
        
        JButton btnNewButton = new JButton("Special Requests ");
        btnNewButton.setFont(new Font("Tahoma", Font.BOLD, 15));
        btnNewButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		
        		add_session adssn = new add_session();
            	adssn.show();
            	dispose();
        		
        	}
        });
        
        btnNewButton_1 = new JButton("");
        btnNewButton_1.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		
        		Main obj = new Main();
     	        obj.show();
     	        dispose();
        	}
        });
        btnNewButton_1.setIcon(new ImageIcon(session_main.class.getResource("/image/home1.png")));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(65)
        					.addComponent(btnNewButton_1, GroupLayout.PREFERRED_SIZE, 97, GroupLayout.PREFERRED_SIZE)
        					.addGap(40)
        					.addComponent(jPanel2, 0, 0, Short.MAX_VALUE))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(205)
        					.addComponent(jLayeredPane1, GroupLayout.PREFERRED_SIZE, 1238, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(202)
        					.addComponent(btnNewButton, GroupLayout.PREFERRED_SIZE, 194, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap())
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(28)
        					.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(jLayeredPane1, GroupLayout.PREFERRED_SIZE, 523, GroupLayout.PREFERRED_SIZE)
        					.addGap(27)
        					.addComponent(btnNewButton, GroupLayout.PREFERRED_SIZE, 47, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(50)
        					.addComponent(btnNewButton_1, GroupLayout.PREFERRED_SIZE, 70, GroupLayout.PREFERRED_SIZE)))
        			.addContainerGap(85, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (normalsession == null) {
            normalsession = new normal_session();
        }
        loader(normalsession);
    }//GEN-LAST:event_jButton2ActionPerformed
consecetive_session consectevie_session;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         if (consectevie_session == null) {
            consectevie_session = new consecetive_session();
        }
        loader(consectevie_session);
    }//GEN-LAST:event_jButton1ActionPerformed
    session_parelel sesion_parelel;
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
          if (sesion_parelel == null) {
            sesion_parelel = new session_parelel();
        }
        loader(sesion_parelel);
    }//GEN-LAST:event_jButton3ActionPerformed
non_overlapping nonoverlapping;
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         if (nonoverlapping == null) {
            nonoverlapping = new non_overlapping();
        }
        loader(nonoverlapping);
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(session_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(session_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(session_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(session_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new session_main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel2;
    private JButton btnNewButton_1;
    // End of variables declaration//GEN-END:variables
private void mm() {
        try {
            ResultSet rs = mydb.search("SELECT * FROM tb_one");
            if (rs.next()) {

                //jLabel1.setText(rs.getString("id"));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void loader(JPanel ff) {

        jLayeredPane1.removeAll();
        ff.setSize(jLayeredPane1.getSize());
        jLayeredPane1.add(ff);
        ff.setVisible(true);
        jLayeredPane1.moveToFront(ff);

    }
}
