/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Controllers.LectureController;

import Controllers.LocationController;
import Controllers.Student_groupController;
import Controllers.SubjectController;
import abc_institute.*;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.SystemColor;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.chart.renderer.category.StandardBarPainter;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Font;
import java.awt.Component;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.JPanel;

/**
 *
 * 
 */
public class statistics extends javax.swing.JFrame {

    /**
     * Creates new form statistics
     */

    public statistics() {
    	setExtendedState(MAXIMIZED_BOTH);
        initComponents();
        try {
            loadData();
            barChart();
        } catch (Exception ex) {
            Logger.getLogger(statistics.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    private void loadData() throws Exception {
        no_of_lectures.setText(LectureController.getInstance().getCount() + "");
        no_of_students.setText(Student_groupController.getInstance().getCount() + "");
        no_of_subjects.setText(SubjectController.getInstance().getCount() + "");
        no_of_rooms.setText(LocationController.getInstance().getCount() + "");
        
        last_lecture.setText(LectureController.getInstance().getLastLecture());
        last_group.setText(Student_groupController.getInstance().getLastStudent());
        last_subject.setText(SubjectController.getInstance().getLastSubject());
    }
    
    private void barChart() throws Exception {
        int classes = LocationController.getInstance().getCountLoc("Lecture Hall");
        int labs = LocationController.getInstance().getCountLoc("Laboratory");
        DefaultPieDataset piedata = new DefaultPieDataset();
        piedata.setValue("Class", classes);
        piedata.setValue("Lab", labs);
        JFreeChart piechart = ChartFactory.createPieChart("Chart", piedata, true, true, true);
        PiePlot pie = (PiePlot) piechart.getPlot();
        pie.setBackgroundPaint(SystemColor.inactiveCaption);
        pie.setSectionPaint(1, new Color(10, 110, 190));
        ChartPanel piePanel = new ChartPanel(piechart);
        piePanel.setAlignmentX(Component.LEFT_ALIGNMENT);
        piePanel.setPreferredSize(new java.awt.Dimension(piechart_panel.getWidth(), piechart_panel.getHeight())); //set better size 
        piePanel.setSize(new java.awt.Dimension(piechart_panel.getWidth(), piechart_panel.getHeight())); //set better size 
        piechart_panel.removeAll();
        piechart_panel.add(piePanel, BorderLayout.CENTER);
        piechart_panel.updateUI();

    }
  
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        last_lecture = new javax.swing.JTextField();
        last_group = new javax.swing.JTextField();
        last_subject = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        piechart_panel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        no_of_lectures = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        no_of_students = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        no_of_subjects = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        no_of_rooms = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 153, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(1857, 992));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "What's New", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        last_lecture.setBackground(new java.awt.Color(255, 255, 255));
        last_lecture.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        last_lecture.setForeground(new java.awt.Color(0, 0, 0));

        last_group.setBackground(new java.awt.Color(255, 255, 255));
        last_group.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        last_group.setForeground(new java.awt.Color(0, 0, 0));
        last_group.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                last_groupKeyTyped(evt);
            }
        });

        last_subject.setBackground(new java.awt.Color(255, 255, 255));
        last_subject.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        last_subject.setForeground(new java.awt.Color(0, 0, 0));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new Font("Dialog", Font.BOLD, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Last Lecturer");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new Font("Dialog", Font.BOLD, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Last Group");

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new Font("Dialog", Font.BOLD, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Last Subject");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGap(24)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel4)
        				.addComponent(jLabel3)
        				.addComponent(jLabel5))
        			.addGap(100)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING, false)
        				.addComponent(last_group)
        				.addComponent(last_subject)
        				.addComponent(last_lecture, GroupLayout.PREFERRED_SIZE, 339, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGap(22)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel4)
        				.addComponent(last_lecture, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabel3)
        				.addComponent(last_group, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(32)
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(last_subject, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel5))
        			.addGap(37))
        );
        jPanel2.setLayout(jPanel2Layout);

        piechart_panel.setBackground(new java.awt.Color(255, 255, 255));
        piechart_panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        piechart_panel.setLayout(new javax.swing.BoxLayout(piechart_panel, javax.swing.BoxLayout.LINE_AXIS));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("ABC Institute");

        jPanel3.setBackground(new Color(224, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        no_of_lectures.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        no_of_lectures.setForeground(new java.awt.Color(0, 0, 0));
        no_of_lectures.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        no_of_lectures.setText("0");

        jLabel2.setFont(new Font("Dialog", Font.BOLD, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Registered Lecturers");

        no_of_students.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        no_of_students.setForeground(new java.awt.Color(0, 0, 0));
        no_of_students.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        no_of_students.setText("0");

        jLabel7.setFont(new Font("Dialog", Font.BOLD, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Registered Groups");

        no_of_subjects.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        no_of_subjects.setForeground(new java.awt.Color(0, 0, 0));
        no_of_subjects.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        no_of_subjects.setText("0");

        jLabel9.setFont(new Font("Dialog", Font.BOLD, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Registered Subjects");

        no_of_rooms.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        no_of_rooms.setForeground(new java.awt.Color(0, 0, 0));
        no_of_rooms.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        no_of_rooms.setText("0");

        jLabel11.setFont(new Font("Dialog", Font.BOLD, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Registered Rooms");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3Layout.setHorizontalGroup(
        	jPanel3Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel3Layout.createSequentialGroup()
        			.addGap(21)
        			.addGroup(jPanel3Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(no_of_subjects, GroupLayout.PREFERRED_SIZE, 145, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel9)
        				.addComponent(no_of_students, GroupLayout.PREFERRED_SIZE, 145, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabel7)
        				.addComponent(jLabel2)
        				.addComponent(no_of_lectures, GroupLayout.PREFERRED_SIZE, 145, GroupLayout.PREFERRED_SIZE)
        				.addGroup(jPanel3Layout.createSequentialGroup()
        					.addGroup(jPanel3Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(no_of_rooms, GroupLayout.PREFERRED_SIZE, 145, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabel11))
        					.addGap(2)))
        			.addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
        	jPanel3Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel3Layout.createSequentialGroup()
        			.addContainerGap(29, Short.MAX_VALUE)
        			.addComponent(jLabel2)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(no_of_lectures, GroupLayout.PREFERRED_SIZE, 80, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jLabel7)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(no_of_students, GroupLayout.PREFERRED_SIZE, 80, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jLabel9)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(no_of_subjects, GroupLayout.PREFERRED_SIZE, 80, GroupLayout.PREFERRED_SIZE)
        			.addGap(42)
        			.addComponent(jLabel11)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(no_of_rooms, GroupLayout.PREFERRED_SIZE, 80, GroupLayout.PREFERRED_SIZE)
        			.addGap(26))
        );
        jPanel3.setLayout(jPanel3Layout);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home1.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new Font("Dialog", Font.BOLD, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Registered Rooms");

        jLabel8.setFont(new Font("Dialog", Font.BOLD, 35)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Statistics");
        
        panel = new JPanel();
        

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap(56, Short.MAX_VALUE)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING, false)
        						.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING, false)
        							.addComponent(jLabel1)
        							.addComponent(piechart_panel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 594, GroupLayout.PREFERRED_SIZE))
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        								.addGroup(jPanel1Layout.createSequentialGroup()
        									.addComponent(jLabel8)
        									.addGap(445))
        								.addGroup(jPanel1Layout.createSequentialGroup()
        									.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        										.addGroup(jPanel1Layout.createSequentialGroup()
        											.addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, 208, GroupLayout.PREFERRED_SIZE)
        											.addGap(55)
        											.addComponent(panel, GroupLayout.PREFERRED_SIZE, 492, GroupLayout.PREFERRED_SIZE))
        										.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 82, GroupLayout.PREFERRED_SIZE))
        									.addGap(343)))
        							.addGap(335)))
        					.addContainerGap(54, Short.MAX_VALUE))
        				.addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(490)
        			.addComponent(jLabel6)
        			.addContainerGap(751, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(17)
        			.addComponent(jLabel6)
        			.addGap(18)
        			.addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
        			.addGap(11)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabel8)
        				.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 68, GroupLayout.PREFERRED_SIZE))
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(18)
        					.addComponent(jPanel3, GroupLayout.PREFERRED_SIZE, 551, GroupLayout.PREFERRED_SIZE)
        					.addContainerGap())
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(33)
        					.addComponent(jLabel1)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addComponent(panel, GroupLayout.PREFERRED_SIZE, 487, GroupLayout.PREFERRED_SIZE)
        							.addContainerGap())
        						.addGroup(jPanel1Layout.createSequentialGroup()
        							.addComponent(piechart_panel, GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
        							.addGap(18)
        							.addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        							.addGap(93))))))
        );
        panel.setLayout(null);
        
        btnNewButton = new JButton("Generate Summary");
        btnNewButton.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		
        		String chartLec = no_of_lectures.getText();
        		String chartStu_grp = no_of_students.getText();
        		String chartSubject = no_of_subjects.getText();
        		
        		DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        		dataset.setValue(new Double(chartLec), "Types", "Lecturers");
        		dataset.setValue(new Double(chartStu_grp), "Types", "Groups");
        		dataset.setValue(new Double(chartSubject), "Types", "Subjects");
        		
        		JFreeChart chart =ChartFactory.createBarChart("Statistics","", "amounts", dataset);
        		CategoryPlot p = chart.getCategoryPlot();
        		p.setRangeGridlinePaint(Color.black);
        		ChartFrame frame = new ChartFrame("Bar Chart for Amounts",chart);
        		frame.setVisible(true);
        		frame.setSize(450,350);
        	}
        });
        btnNewButton.setBounds(10, 10, 157, 30);
        panel.add(btnNewButton);
        
        panel_1 = new JPanel();
        panel_1.setBounds(10, 62, 472, 415);
        panel.add(panel_1);
        jPanel1.setLayout(jPanel1Layout);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void last_groupKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_last_groupKeyTyped
        char c = evt.getKeyChar();
        if (!(Character.isDigit(c))) {
            evt.consume();
        }
    }//GEN-LAST:event_last_groupKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Main obj = new Main();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(statistics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new statistics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField last_group;
    private javax.swing.JTextField last_lecture;
    private javax.swing.JTextField last_subject;
    private javax.swing.JLabel no_of_lectures;
    private javax.swing.JLabel no_of_rooms;
    private javax.swing.JLabel no_of_students;
    private javax.swing.JLabel no_of_subjects;
    private javax.swing.JPanel piechart_panel;
    private JPanel panel;
    private JButton btnNewButton;
    private JPanel panel_1;
}
